### ISSUE TITLE
prefer_snake_case

### ISSUE THREAD

**Issue by gtm-nayan** [pngwn/svelte-bot#20]
toAlignWithTheOtherSvelteRepos

to_align_with_the_other_svelte_repos

I rest my case.

**Comment by pngwn** [comment]
snake case always worth it.

**Comment by ghostdevv** [comment]
can we close this? @gtm-nayan

**Comment by gtm-nayan** [comment]
we've converted pretty much everything afaik (*cough* jellycommands when *cough*), so sure

**Comment by pngwn** [comment]
Only internal stuff is required to be snake case for svelte stuff, third parties are what they are.
