### ISSUE TITLE
Feature - Mark thread as Solved

### ISSUE THREAD

**Issue by FractalHQ** [pngwn/svelte-bot#25]
It would be cool if we had a way to mark a help thread as solved.  That way, it would be easier to locate unsolved threads in `#svelte-help`.

Perhaps something like `/solved` could prepend a ✅  to the threads title?

Also (this is probably a bad idea) it could be cool to do `/solved @username` to keep track of how how many threads users have solved.  This could be used for leaderboards / podcast shoutouts / proving to my mom I'm worthy of love / etc.

**Comment by ghostdevv** [comment]
Great idea, thread titles can be `❓- <>` and when solved can be `✅ - <>`.

> Also (this is probably a bad idea) it could be cool to do /solved @username to keep track of how how many threads users have solved. This could be used for leaderboards / podcast shoutouts / proving to my mom I'm worthy of love / etc.

I like this idea as may promote people helping more and also promote the use of /thread solved, though would need @pngwn to sign off on this 

p.s. unsure the amount of points you would need to prove to your mum you are worthy of her love but that can be looked into 🥲

**Comment by pngwn** [comment]
> unsure the amount of points you would need to prove to your mum you are worthy of her love but that can be looked into 🥲

It is  seven. 

Brady is basically in my head cos I discussed this with Kev earlier. Definitely +1 from me. I’d actually like to think of a way to say which comment solved it but I don’t know how that would work. I think the tick/ question mark in the title would be a great first pass.

**Comment by gtm-nayan** [comment]
This'll likely be better as a message context menu command than a slash.

Another thing to consider,
emotes in the name might mess with the character limit if discords transforms them to the colon syntax. Haven't tested that yes.

**Comment by ghostdevv** [comment]
Awesome I will get this finished then when I can fix the mess I made in a different pr xD I was going to do a button thing and a opening message, you beat me to the opening message and then I will do a slash command and the button after we got your pr done. Will take a look at fixing that tommorrow @gtm-nayan
