### ISSUE TITLE
Allow to tag multiple users in /thread solve

### ISSUE THREAD

**Issue by TheOnlyTails** [pngwn/svelte-bot#31]
Sometimes, multiple users help to solve a question, and it's great to let people give credit to everyone.

I don't know if discord has varargs for slash commands, but a solution would be nice to have.

**Comment by gtm-nayan** [comment]
Variadic arguments are not a thing yet. And I read somewhere that they're really low on discord's priority list.

How about something like this? 
![image](https://user-images.githubusercontent.com/50981692/153696603-37f68ae8-6a54-48b4-98ff-eab3588513fc.png)

When someone runs `/thread solve` we send a list of the thread participants as buttons. Then we increment the user's stats whenever the button is clicked and then disable the button.

**Comment by TheOnlyTails** [comment]
That would be awesome, though you should add a "none of them" button just in case the user figured it out themselves.

**Comment by TheOnlyTails** [comment]
Additionally, is there a way to put all buttons in one row?

**Comment by gtm-nayan** [comment]
> though you should add a "none of them" button just in case the user figured it out themselves.
I don't think that'd be needed. `/thread solve` can be ran without any args and the buttons would be on the reply to it. If they solve it themselves they can just not click on anyone, and the thread would still be marked as solved.

> is there a way to put all buttons in one row?
Yes, that's how it'll be. I just used inspect element for the mockup so they got stacked.

@pngwn @ghostdevv thoughts?
