### ISSUE TITLE
Add note on /thread solve

### ISSUE THREAD

**Issue by ghostdevv** [pngwn/svelte-bot#41]
When #40 is merged would be good for typing `/thread solve` in the questions channel to send a message saying to use `/question 
solve`

**Comment by ghostdevv** [comment]
I just realised that `/thread solve` has been removed, I don't know if theres much point in doing this - thoughts? @gtm-nayan

**Comment by gtm-nayan** [comment]
Yeah, re-adding a command just for a replacement notice doesn't seem worth it.
